# Generated by Django 3.0.3 on 2020-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201125_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.IntegerField(blank=True)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('Designation', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='Details',
            field=models.ManyToManyField(blank=True, to='home.Detail'),
        ),
    ]
