# Generated by Django 3.0.3 on 2020-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201125_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
