# Generated by Django 3.0.3 on 2020-11-26 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201125_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='Events',
            field=models.ManyToManyField(blank=True, to='home.Event'),
        ),
    ]
