# Generated by Django 3.0.3 on 2020-11-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201126_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='Events',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Home'),
        ),
    ]
