# Generated by Django 3.0.3 on 2020-11-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201126_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Events',
            field=models.ManyToManyField(blank=True, to='home.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='home.Home'),
        ),
    ]
