# Generated by Django 3.0.3 on 2020-11-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201126_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='home.Home'),
        ),
    ]
