# Generated by Django 3.0.3 on 2020-11-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201126_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='Events',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
