# Generated by Django 3.0.3 on 2020-11-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201126_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, default='', help_text='Day of the event', verbose_name='Day of the event')),
                ('start_time', models.TimeField(default='', help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(default='', help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, default='', help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Home')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
