# Generated by Django 3.0.3 on 2020-11-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201126_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Add_Event',
            field=models.ManyToManyField(blank=True, to='home.Event'),
        ),
    ]
