# Generated by Django 3.0.3 on 2020-11-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201126_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='home.Home'),
        ),
    ]
